SDK_DIR       ?= /srv/armv7-thumb-min-debug/root/VGLite
KERNEL_DIR    ?= /home/software/Linux/linux-2.6.29
CROSS_COMPILE ?= /home/software/Linux/arm-2011.09/bin/arm-none-linux-gnueabi-
CC            ?= $(CROSS_COMPILE)gcc

DEBUG       ?= 0
CPU_ARCH    ?= armv7-a
FLOAT_ABI   ?=
ENABLE_PCIE ?= 0

ifneq ($(CPU_ARCH),0)
CFLAGS += -march=$(CPU_ARCH)
endif
ifneq ($(FPU),)
  CFLAGS += -mfpu=$(FPU)
endif
ifneq ($(FLOAT_ABI),)
  CFLAGS += -mfloat-abi=$(FLOAT_ABI)
endif

CFLAGS += -fPIC -std=c99 -fno-strict-aliasing -D_GNU_SOURCE

ifeq ($(DEBUG), 1)
CFLAGS += -g -O0 -DDEBUG -D_DEBUG -Wno-cpp
else
CFLAGS += -O2 -Werror
endif

